#!/bin/bash

project_name=$2
type=$(echo "$1" | sed 's/.*/\U&/')
date=$(date +%d.%m.%Y)

if [[ -z "$type" ]]; then
    echo "Project type can not be empty!"
    exit 1
fi

if [[ -z "$project_name" ]]; then
    echo "Project name can not be empty!"
    exit 1
fi

cp -r $HOME/.config/scripts/project_templates/$type ./$project_name
cd $project_name

# TODO: this results in an error when nothing to be replaced is found
grep -rl "<project_name>" | xargs -r sed -i "s/<project_name>/$project_name/g" 2>&1 > /dev/null
grep -rl "<date>" | xargs -r sed -i "s/<date>/$date/g" 2>&1 > /dev/null

git init . > /dev/null
echo "$type Project $project_name has been created successfully."
exit 0
