#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Project Name can not be empty!"
    exit 1
fi

cp -r $HOME/.config/scripts/CPP ./$1
cd $1

grep -rl "XXXXX" | xargs sed -i "s/XXXXX/$1/g"

cd ..

echo "Project $1 has been created successfully."
exit 0

